name = "Dart"
grammar = "dart"
path_suffixes = ["dart"]
line_comments = ["// ", "/// "]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
